# Generated by Django 3.0.6 on 2020-05-28 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0002_auto_20200528_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='dns_id',
            new_name='dns',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='service_id',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='service_dns',
            old_name='dns_id',
            new_name='dns',
        ),
        migrations.RenameField(
            model_name='service_dns',
            old_name='service_id',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='service_id',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='user_id',
            new_name='user',
        ),
    ]
