# Generated by Django 3.0.6 on 2020-06-03 12:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0002_auto_20200603_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned_ip', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('result', models.CharField(max_length=50)),
                ('dns', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_side.DNS')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_side.Service')),
                ('vpn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_side.VPN')),
            ],
        ),
        migrations.RemoveField(
            model_name='returnedip',
            name='vpn',
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.DeleteModel(
            name='ReturnedIP',
        ),
        migrations.AddField(
            model_name='response',
            name='responses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_side.Responses'),
        ),
    ]
