# Generated by Django 3.0.6 on 2020-05-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0003_auto_20200528_2146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
