# Generated by Django 3.0.6 on 2020-06-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0004_queries_validity'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='label',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vpn',
            name='ovpn_config',
            field=models.BinaryField(editable=True),
        ),
    ]
