# Generated by Django 3.0.6 on 2020-05-28 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0004_auto_20200528_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payment_id', models.CharField(max_length=20)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_side.Service')),
            ],
        ),
    ]
