# Generated by Django 3.0.6 on 2020-05-28 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0005_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='service',
        ),
        migrations.AddField(
            model_name='order',
            name='subscription',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='user_side.Subscription'),
            preserve_default=False,
        ),
    ]
