# Generated by Django 3.0.6 on 2020-05-28 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0006_auto_20200528_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50, null=True)),
                ('dns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='user_side.DNS')),
            ],
        ),
        migrations.AlterField(
            model_name='dns',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='user_side.Location'),
        ),
    ]
