# Generated by Django 3.0.6 on 2020-06-17 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0007_auto_20200617_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='web_address',
        ),
    ]
