# Generated by Django 3.0.6 on 2020-06-18 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0011_vpn_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dns',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_side.Location'),
        ),
        migrations.AlterField(
            model_name='vpn',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_side.Location'),
        ),
    ]
