# Generated by Django 3.0.6 on 2020-06-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0013_auto_20200628_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='admin',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
