# Generated by Django 3.0.6 on 2020-05-30 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DNS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('IP', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('IP', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='VPN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nlconfig_file', models.BinaryField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_side.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_side.Service')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service_DNS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dns', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_side.DNS')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_side.Service')),
                ('vpn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_side.VPN')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payment_id', models.CharField(max_length=20)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_side.Subscription')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('returned_ip', models.GenericIPAddressField()),
                ('result', models.CharField(max_length=50)),
                ('dns', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_side.DNS')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_side.Service')),
                ('vpn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_side.VPN')),
            ],
        ),
        migrations.AddField(
            model_name='dns',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_side.Location'),
        ),
    ]
