# Generated by Django 3.0.6 on 2020-06-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0003_auto_20200603_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='queries',
            name='validity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
