# Generated by Django 3.0.6 on 2020-06-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0005_auto_20200613_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='dns',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
