# Generated by Django 3.0.6 on 2020-06-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0006_dns_public'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='responses',
            constraint=models.UniqueConstraint(fields=('dns', 'date', 'vpn', 'service'), name='unique row constraint'),
        ),
    ]
