# Generated by Django 3.0.6 on 2020-06-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0008_auto_20200617_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpn',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
