# Generated by Django 3.0.6 on 2020-06-18 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0009_vpn_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vpn',
            name='public',
        ),
    ]
